server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  zipkin:
    base-url: http://localhost:9411
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include:*